# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honors', '0002_auto_20151217_0626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='achievement_type',
            field=models.CharField(choices=[('promo', 'Поощрение'), ('recovery', 'Взыскание')], max_length=32),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='allowance',
            field=models.IntegerField(verbose_name='Надбавка (может быть отрицательной)'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='date',
            field=models.DateField(verbose_name='Дата награждения/взыскания'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Название события'),
        ),
        migrations.AlterField(
            model_name='prize',
            name='prize',
            field=models.PositiveSmallIntegerField(verbose_name='Премия'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='destination_day',
            field=models.DateField(verbose_name='День с которого действует зарплата'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='salary',
            field=models.PositiveSmallIntegerField(verbose_name='Зарплата'),
        ),
    ]
