# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerhigheducation',
            name='education_type',
            field=models.CharField(max_length=128, verbose_name='Тип образования'),
        ),
        migrations.AlterField(
            model_name='workerhigheducation',
            name='from_date',
            field=models.DateField(verbose_name='Дата начала обучения'),
        ),
        migrations.AlterField(
            model_name='workerhigheducation',
            name='graduation_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Год выпуска'),
        ),
        migrations.AlterField(
            model_name='workerhigheducation',
            name='to_date',
            field=models.DateField(verbose_name='Дата окончания обучения'),
        ),
        migrations.AlterField(
            model_name='workersecondaryeducation',
            name='from_date',
            field=models.DateField(verbose_name='Дата начала обучения'),
        ),
        migrations.AlterField(
            model_name='workersecondaryeducation',
            name='graduation_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Год выпуска'),
        ),
        migrations.AlterField(
            model_name='workersecondaryeducation',
            name='to_date',
            field=models.DateField(verbose_name='Дата окончания обучения'),
        ),
    ]
