# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_auto_20151220_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposition',
            name='from_date',
            field=models.DateField(verbose_name='Дата начала работы на данной позиции'),
        ),
        migrations.AlterField(
            model_name='jobposition',
            name='organization',
            field=models.CharField(blank=True, max_length=128, verbose_name='Название организации'),
        ),
        migrations.AlterField(
            model_name='jobposition',
            name='position',
            field=models.CharField(max_length=128, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='jobposition',
            name='to_date',
            field=models.DateField(blank=True, verbose_name='Дата окончания работы на данной позиции'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='avatar',
            field=models.ImageField(blank=True, help_text="User's avatar", null=True, upload_to='images/web_users/'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='birth_place',
            field=models.CharField(max_length=255, null=True, verbose_name='Место рождения'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='birthday',
            field=models.DateField(null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='marital_status',
            field=models.CharField(choices=[('Single', 'Не женат/не замужем'), ('In relation ship', 'Встречаюсь'), ('Engaged', 'Помолвлен(а)'), ('Married', 'Женат/замужем'), ('Widower', 'Вдова/вдовец'), ('In love', 'Влюбен(а)'), ("It's complicated", 'Все сложно'), ('Actively searching', 'В активном поиске'), ("I'm programmer", 'Я - программист')], max_length=50, null=True, verbose_name='Семейное положение'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='patronymic',
            field=models.CharField(max_length=255, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='sex',
            field=models.BooleanField(default=False, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='user_type',
            field=models.CharField(choices=[('Admin', 'Администратор'), ('Human resources Department', 'Отдел кадров'), ('Accounting', 'Бухгалтерия'), ('Chief', 'Начальник'), ('Trade union', 'Профком'), ('Stuff', 'Персонал')], max_length=64, null=True, verbose_name='Тип пользователя'),
        ),
        migrations.AlterField(
            model_name='workerchild',
            name='birthday',
            field=models.DateField(verbose_name='Дата рождения ребенка'),
        ),
        migrations.AlterField(
            model_name='workerchild',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имя ребенка'),
        ),
        migrations.AlterField(
            model_name='workerchild',
            name='sex',
            field=models.BooleanField(default=False, verbose_name='Пол'),
        ),
    ]
