# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 19:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0004_auto_20151221_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposition',
            name='position_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='department.DepartmentJobPosition', verbose_name='Должность на нашем предприятии'),
        ),
    ]
