# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0005_auto_20151221_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposition',
            name='to_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания работы на данной позиции'),
        ),
    ]
